# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainTela.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainTela(object):
    def setupUi(self, mainTela):
        mainTela.setObjectName("mainTela")
        mainTela.resize(582, 491)
        self.labelNome = QtWidgets.QLabel(mainTela)
        self.labelNome.setGeometry(QtCore.QRect(210, 10, 191, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelNome.sizePolicy().hasHeightForWidth())
        self.labelNome.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelNome.setFont(font)
        self.labelNome.setObjectName("labelNome")
        self.line = QtWidgets.QFrame(mainTela)
        self.line.setGeometry(QtCore.QRect(10, 30, 581, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(mainTela)
        self.line_2.setGeometry(QtCore.QRect(330, 120, 261, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(mainTela)
        self.line_3.setGeometry(QtCore.QRect(440, 90, 20, 40))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(mainTela)
        self.line_4.setGeometry(QtCore.QRect(0, 458, 621, 30))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_4 = QtWidgets.QLabel(mainTela)
        self.label_4.setGeometry(QtCore.QRect(0, 470, 571, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.line_5 = QtWidgets.QFrame(mainTela)
        self.line_5.setGeometry(QtCore.QRect(30, 70, 261, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(mainTela)
        self.line_6.setGeometry(QtCore.QRect(140, 40, 20, 40))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_5 = QtWidgets.QLabel(mainTela)
        self.label_5.setGeometry(QtCore.QRect(50, 40, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(mainTela)
        self.label_6.setGeometry(QtCore.QRect(190, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.labelSeguidores = QtWidgets.QLabel(mainTela)
        self.labelSeguidores.setGeometry(QtCore.QRect(50, 61, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelSeguidores.setFont(font)
        self.labelSeguidores.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSeguidores.setObjectName("labelSeguidores")
        self.labelSeguindo = QtWidgets.QLabel(mainTela)
        self.labelSeguindo.setGeometry(QtCore.QRect(180, 60, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelSeguindo.setFont(font)
        self.labelSeguindo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSeguindo.setObjectName("labelSeguindo")
        self.line_7 = QtWidgets.QFrame(mainTela)
        self.line_7.setGeometry(QtCore.QRect(310, 40, 21, 401))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.sairButton = QtWidgets.QPushButton(mainTela)
        self.sairButton.setGeometry(QtCore.QRect(490, 440, 75, 23))
        self.sairButton.setObjectName("sairButton")
        self.labelLikes = QtWidgets.QLabel(mainTela)
        self.labelLikes.setGeometry(QtCore.QRect(350, 111, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelLikes.setFont(font)
        self.labelLikes.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLikes.setObjectName("labelLikes")
        self.label_7 = QtWidgets.QLabel(mainTela)
        self.label_7.setGeometry(QtCore.QRect(350, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.labelComent = QtWidgets.QLabel(mainTela)
        self.labelComent.setGeometry(QtCore.QRect(480, 111, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelComent.setFont(font)
        self.labelComent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelComent.setObjectName("labelComent")
        self.label_8 = QtWidgets.QLabel(mainTela)
        self.label_8.setGeometry(QtCore.QRect(470, 90, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.listWidget = QtWidgets.QListWidget(mainTela)
        self.listWidget.setGeometry(QtCore.QRect(10, 110, 291, 321))
        self.listWidget.setObjectName("listWidget")
        self.label_11 = QtWidgets.QLabel(mainTela)
        self.label_11.setGeometry(QtCore.QRect(100, 90, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.labelFollow = QtWidgets.QLabel(mainTela)
        self.labelFollow.setGeometry(QtCore.QRect(350, 161, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelFollow.setFont(font)
        self.labelFollow.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFollow.setObjectName("labelFollow")
        self.labelUnfollow = QtWidgets.QLabel(mainTela)
        self.labelUnfollow.setGeometry(QtCore.QRect(480, 161, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelUnfollow.setFont(font)
        self.labelUnfollow.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUnfollow.setObjectName("labelUnfollow")
        self.label_9 = QtWidgets.QLabel(mainTela)
        self.label_9.setGeometry(QtCore.QRect(470, 140, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.line_8 = QtWidgets.QFrame(mainTela)
        self.line_8.setGeometry(QtCore.QRect(330, 170, 261, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(mainTela)
        self.line_9.setGeometry(QtCore.QRect(440, 140, 20, 40))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_10 = QtWidgets.QLabel(mainTela)
        self.label_10.setGeometry(QtCore.QRect(350, 140, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.line_10 = QtWidgets.QFrame(mainTela)
        self.line_10.setGeometry(QtCore.QRect(323, 70, 261, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label_12 = QtWidgets.QLabel(mainTela)
        self.label_12.setGeometry(QtCore.QRect(400, 50, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")

        self.retranslateUi(mainTela)
        QtCore.QMetaObject.connectSlotsByName(mainTela)

    def retranslateUi(self, mainTela):
        _translate = QtCore.QCoreApplication.translate
        mainTela.setWindowTitle(_translate("mainTela", "Instaboost - Beta"))
        self.labelNome.setText(_translate("mainTela", "Nomedousuario insta"))
        self.label_4.setText(_translate("mainTela", "Criado por diversão        -         duvidas e sugestões:        andrewsegas@gmail.com"))
        self.label_5.setText(_translate("mainTela", "Followers"))
        self.label_6.setText(_translate("mainTela", "Following"))
        self.labelSeguidores.setText(_translate("mainTela", "0"))
        self.labelSeguindo.setText(_translate("mainTela", "0"))
        self.sairButton.setText(_translate("mainTela", "Log out"))
        self.labelLikes.setText(_translate("mainTela", "0"))
        self.label_7.setText(_translate("mainTela", "Likes:"))
        self.labelComent.setText(_translate("mainTela", "0"))
        self.label_8.setText(_translate("mainTela", "Comments:"))
        self.label_11.setText(_translate("mainTela", "Atividade:"))
        self.labelFollow.setText(_translate("mainTela", "0"))
        self.labelUnfollow.setText(_translate("mainTela", "0"))
        self.label_9.setText(_translate("mainTela", "Unfollow:"))
        self.label_10.setText(_translate("mainTela", "Follow:"))
        self.label_12.setText(_translate("mainTela", "Counter:"))